spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    url: jdbc:h2:mem:ordersdb
    password: ENC(rAYaQjYJzEh3KXEtLyCJEMmOUVIFRbSL4PsZCwG+9PCI5fNboLeCC66U+VMqVUvi)
  h2:
    console:
      enabled: 'true'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  application:
    name: orders-ms
server:
  port: '8080'
